package com.timgeldof.gustfinder.network.models.marine_weather_api

data class Hourly (

	val time : Int?,
	val tempC : Int?,
	val tempF : Int?,
	val windspeedMiles : Int?,
	val windspeedKmph : Int?,
	val winddirDegree : Int?,
	val winddir16Point : String?,
	val weatherCode : Int?,
	val weatherIconUrl : List<WeatherIconUrl>?,
	val weatherDesc : List<WeatherDesc>?,
	val precipMM : Double?,
	val precipInches : Double?,
	val humidity : Int?,
	val visibility : Int?,
	val visibilityMiles : Int?,
	val pressure : Int?,
	val pressureInches : Int?,
	val cloudcover : Int?,
	val heatIndexC : Int?,
	val heatIndexF : Int?,
	val dewPointC : Int?,
	val dewPointF : Int?,
	val windChillC : Int?,
	val windChillF : Int?,
	val windGustMiles : Int?,
	val windGustKmph : Int?,
	val feelsLikeC : Int?,
	val feelsLikeF : Int?,
	val sigHeight_m : Double?,
	val swellHeight_m : Double?,
	val swellHeight_ft : Double?,
	val swellDir : Int?,
	val swellDir16Point : String?,
	val swellPeriod_secs : Double?,
	val waterTemp_C : Int?,
	val waterTemp_F : Int?
)